name = "qa-elemental-chat"
type = "webpack"
account_id = "18ff2b4e6205b938652998cfca0d8cff"

route = "elemental-chat.qa.holotest.net/*"
zone_id = "35f34e8f9d04ef8c87283ea9fb812989"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.mainnet]
name = "elemental-chat"
route = "elemental-chat.holo.host/*"
workers_dev = true
