name: Continuous Deployment for Scaletest

on:
  push:
    branches:
      - scaletest

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - name: Build site
        run: yarn run build:holo-scale-test
      - name: Publish to DevNet
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: scaletest
