name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
    - name: Use Nix
      uses: cachix/install-nix-action@v12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure Nix substituters
      run: |
        set -xe
        mkdir -p ~/.config/nix/
        cp ./.github/nix.conf ~/.config/nix/
    - name: Prepare Nix environment
      run: nix-shell --command "echo Completed"
    - name: Check Holochain version
      run: nix-shell --command "holochain -V"
    - name: Install node-modules
      run: yarn install
    - name: Correct holochain-conductor-api dep build
      run: yarn correct:hc-conductor-api-build
    - name: Run holochain-environment unit tests
      run: yarn test:unit-hc
    - name: Run holochain-environment unit tests
      run: yarn test:unit-holo
    - name: Run holochain-environment integration tests
      run: nix-shell --run 'yarn test:holochain-ci'
