name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
    - name: Use Nix
      uses: cachix/install-nix-action@v12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure Nix substituters
      run: |
        set -xe
        mkdir -p ~/.config/nix/
        cp ./.github/nix.conf ~/.config/nix/
    - name: Prepare Nix environment
      run: nix-shell --command "echo Completed"
    - name: Check Holochain version
      run: nix-shell --command "holochain -V"
    - name: Install dependencies
      run: |
            sudo service lightdm start
            export DISPLAY=:0.0
    - name: Install Chromedriver latest version
      run: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
    - name: Install node-modules
      run:  yarn install
    - name: Run holochain-environment integration tests
      run: nix-shell --run 'yarn test:holochain-ci'
    - name: Run holo-environment authentication test
      run: nix-shell --run 'yarn test:holo-host-ci'
